#!/bin/bash
set -e

export DATE=$(date +%Y%m%dT%H%M)

env | sort

docker build \
  --build-arg BUILD_DATE=${DATE} \
  --build-arg VCS_REF=${CIRCLE_SHA1:0:7} \
  -t opensm src/

echo "Images"
docker images
